In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.10.5)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.23.2->pandas>=1.0.0->ucimlrepo) (2024.2.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [3]:
from ucimlrepo import fetch_ucirepo 

covertype = fetch_ucirepo(id=31) # fetch dataset

x = covertype.data.features #features
y = covertype.data.targets  #class

In [4]:
x.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y.head()

   Cover_Type
0           5
1           5
2           2
3           2
4           5

In [6]:
print(x.shape,y.shape)

(581012, 54) (581012, 1)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
# train test split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, random_state=42, test_size=.30)

In [10]:
print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

(406708, 54) (406708, 1)
(174304, 54) (174304, 1)

In [11]:
# test and validation
x_test, x_val, y_test, y_val = train_test_split(xtest, ytest, random_state=42, test_size=.50)

In [12]:
print(x_test.shape,y_test.shape)
print(x_val.shape,y_val.shape)

(87152, 54) (87152, 1)
(87152, 54) (87152, 1)

In [13]:
import xgboost as xgb
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import accuracy_score, classification_report

# XGBoost

In [15]:
xgboost  = xgb.XGBClassifier(eval_metric='logloss', random_state=42)
xgboost.fit(xtrain,ytrain)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3 4 5 6], got [1 2 3 4 5 6 7]

In [16]:
print(ytrain.shape,y_test.shape)

(406708, 1) (87152, 1)

In [17]:
print("-----ytrain value count------")
print(ytrain.value_counts())
print("-----y_test value count------")
print(y_test.value_counts())

-----ytrain value count------
Cover_Type
2             198223
1             148284
3              25116
7              14441
6              12140
5               6552
4               1952
Name: count, dtype: int64
-----y_test value count------
Cover_Type
2             42414
1             31897
3              5341
7              3015
6              2636
5              1448
4               401
Name: count, dtype: int64

In [18]:
y.value_counts()

Cover_Type
2             283301
1             211840
3              35754
7              20510
6              17367
5               9493
4               2747
Name: count, dtype: int64

In [19]:
y_new = y-1
y_new.value_counts()

Cover_Type
1             283301
0             211840
2              35754
6              20510
5              17367
4               9493
3               2747
Name: count, dtype: int64

In [20]:
# train test split
xtrain1, xtest1, ytrain1, ytest1 = train_test_split(x, y_new, random_state=42, test_size=.30)

In [21]:
print(xtrain1.shape,ytrain1.shape)
print(xtest1.shape,ytest1.shape)
print("-----ytrain1 value count------")
print(ytrain1.value_counts())
print("-----ytest1 value count------")
print(ytest1.value_counts())

(406708, 54) (406708, 1)
(174304, 54) (174304, 1)
-----ytrain1 value count------
Cover_Type
1             198223
0             148284
2              25116
6              14441
5              12140
4               6552
3               1952
Name: count, dtype: int64
-----ytest1 value count------
Cover_Type
1             85078
0             63556
2             10638
6              6069
5              5227
4              2941
3               795
Name: count, dtype: int64

In [22]:
# test and validation
x_test1, x_val1, y_test1, y_val1 = train_test_split(xtest1, ytest1, random_state=42, test_size=.50)

In [23]:
print(x_test1.shape,y_test1.shape)
print(x_val1.shape,y_val1.shape)
print("-----y_test1 value count------")
print(y_test1.value_counts())
print("-----y_val1 value count------")
print(y_val1.value_counts())

(87152, 54) (87152, 1)
(87152, 54) (87152, 1)
-----y_test1 value count------
Cover_Type
1             42414
0             31897
2              5341
6              3015
5              2636
4              1448
3               401
Name: count, dtype: int64
-----y_val1 value count------
Cover_Type
1             42664
0             31659
2              5297
6              3054
5              2591
4              1493
3               394
Name: count, dtype: int64

In [25]:
xgboost1 = xgb.XGBClassifier(eval_metric='logloss', random_state=42)
xgboost1.fit(xtrain1,ytrain1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, objective='multi:softprob', ...)

In [26]:
xgboost1_y_predict = xgboost1.predict(x_test1)

In [27]:
accuracy_score(y_test1,xgboost1_y_predict)

0.8660615935377272

In [28]:
xgboost1.score(xtrain1,ytrain1)

0.8786967554117451

# CatBoost

In [29]:
cat_model = CatBoostClassifier(random_state=42)
cat_model.fit(xtrain1,ytrain1)

Learning rate set to 0.107497
0:	learn: 1.6596468	total: 301ms	remaining: 5m
1:	learn: 1.4802280	total: 535ms	remaining: 4m 26s
2:	learn: 1.3508880	total: 729ms	remaining: 4m 2s
3:	learn: 1.2537283	total: 900ms	remaining: 3m 44s
4:	learn: 1.1763809	total: 1.07s	remaining: 3m 32s
5:	learn: 1.1126287	total: 1.25s	remaining: 3m 26s
6:	learn: 1.0576846	total: 1.42s	remaining: 3m 22s
7:	learn: 1.0125113	total: 1.6s	remaining: 3m 18s
8:	learn: 0.9716682	total: 1.78s	remaining: 3m 15s
9:	learn: 0.9362388	total: 1.95s	remaining: 3m 13s
10:	learn: 0.9047341	total: 2.13s	remaining: 3m 11s
11:	learn: 0.8778276	total: 2.31s	remaining: 3m 9s
12:	learn: 0.8527947	total: 2.48s	remaining: 3m 8s
13:	learn: 0.8315963	total: 2.65s	remaining: 3m 6s
14:	learn: 0.8145325	total: 2.81s	remaining: 3m 4s
15:	learn: 0.7950816	total: 2.98s	remaining: 3m 3s
16:	learn: 0.7789888	total: 3.14s	remaining: 3m 1s
17:	learn: 0.7644675	total: 3.32s	remaining: 3m 1s
18:	learn: 0.7527366	total: 3.49s	remaining: 3m
19:	learn: 0.7397704	total: 3.68s	remaining: 3m
20:	learn: 0.7294826	total: 3.84s	remaining: 2m 58s
21:	learn: 0.7191195	total: 4.02s	remaining: 2m 58s
22:	learn: 0.7107955	total: 4.18s	remaining: 2m 57s
23:	learn: 0.7033826	total: 4.35s	remaining: 2m 56s
24:	learn: 0.6965837	total: 4.5s	remaining: 2m 55s
25:	learn: 0.6901734	total: 4.65s	remaining: 2m 54s
26:	learn: 0.6846192	total: 4.82s	remaining: 2m 53s
27:	learn: 0.6779462	total: 4.98s	remaining: 2m 52s
28:	learn: 0.6724716	total: 5.14s	remaining: 2m 52s
29:	learn: 0.6677013	total: 5.31s	remaining: 2m 51s
30:	learn: 0.6635266	total: 5.46s	remaining: 2m 50s
31:	learn: 0.6587434	total: 5.63s	remaining: 2m 50s
32:	learn: 0.6559593	total: 5.78s	remaining: 2m 49s
33:	learn: 0.6509497	total: 5.96s	remaining: 2m 49s
34:	learn: 0.6483949	total: 6.12s	remaining: 2m 48s
35:	learn: 0.6454380	total: 6.3s	remaining: 2m 48s
36:	learn: 0.6403972	total: 6.49s	remaining: 2m 48s
37:	learn: 0.6381044	total: 6.64s	remaining: 2m 48s
38:	learn: 0.6352601	total: 6.8s	remaining: 2m 47s
39:	learn: 0.6312032	total: 6.97s	remaining: 2m 47s
40:	learn: 0.6286193	total: 7.12s	remaining: 2m 46s
41:	learn: 0.6261628	total: 7.27s	remaining: 2m 45s
42:	learn: 0.6238506	total: 7.43s	remaining: 2m 45s
43:	learn: 0.6213847	total: 7.6s	remaining: 2m 45s
44:	learn: 0.6202249	total: 7.75s	remaining: 2m 44s
45:	learn: 0.6177357	total: 7.91s	remaining: 2m 44s
46:	learn: 0.6153988	total: 8.07s	remaining: 2m 43s
47:	learn: 0.6132315	total: 8.23s	remaining: 2m 43s
48:	learn: 0.6105842	total: 8.41s	remaining: 2m 43s
49:	learn: 0.6081752	total: 8.57s	remaining: 2m 42s
50:	learn: 0.6056878	total: 8.75s	remaining: 2m 42s
51:	learn: 0.6030481	total: 8.94s	remaining: 2m 42s
52:	learn: 0.5996044	total: 9.13s	remaining: 2m 43s
53:	learn: 0.5979747	total: 9.29s	remaining: 2m 42s
54:	learn: 0.5959498	total: 9.44s	remaining: 2m 42s
55:	learn: 0.5936872	total: 9.6s	remaining: 2m 41s
56:	learn: 0.5925932	total: 9.75s	remaining: 2m 41s
57:	learn: 0.5909208	total: 9.91s	remaining: 2m 41s
58:	learn: 0.5890731	total: 10.1s	remaining: 2m 40s
59:	learn: 0.5883085	total: 10.2s	remaining: 2m 40s
60:	learn: 0.5860232	total: 10.4s	remaining: 2m 40s
61:	learn: 0.5843939	total: 10.6s	remaining: 2m 40s
62:	learn: 0.5823125	total: 10.8s	remaining: 2m 40s
63:	learn: 0.5806416	total: 11s	remaining: 2m 40s
64:	learn: 0.5791195	total: 11.1s	remaining: 2m 40s
65:	learn: 0.5779989	total: 11.3s	remaining: 2m 39s
66:	learn: 0.5761947	total: 11.5s	remaining: 2m 39s
67:	learn: 0.5738908	total: 11.7s	remaining: 2m 39s
68:	learn: 0.5725452	total: 11.8s	remaining: 2m 39s
69:	learn: 0.5710000	total: 12s	remaining: 2m 39s
70:	learn: 0.5691747	total: 12.2s	remaining: 2m 39s
71:	learn: 0.5676666	total: 12.3s	remaining: 2m 38s
72:	learn: 0.5656885	total: 12.5s	remaining: 2m 38s
73:	learn: 0.5643745	total: 12.7s	remaining: 2m 38s
74:	learn: 0.5630992	total: 12.8s	remaining: 2m 38s
75:	learn: 0.5616730	total: 13s	remaining: 2m 37s
76:	learn: 0.5607161	total: 13.2s	remaining: 2m 37s
77:	learn: 0.5598427	total: 13.3s	remaining: 2m 37s
78:	learn: 0.5586711	total: 13.5s	remaining: 2m 37s
79:	learn: 0.5574019	total: 13.7s	remaining: 2m 37s
80:	learn: 0.5560813	total: 13.8s	remaining: 2m 36s
81:	learn: 0.5550896	total: 14s	remaining: 2m 36s
82:	learn: 0.5537327	total: 14.1s	remaining: 2m 36s
83:	learn: 0.5523372	total: 14.3s	remaining: 2m 36s
84:	learn: 0.5509992	total: 14.5s	remaining: 2m 35s
85:	learn: 0.5501435	total: 14.7s	remaining: 2m 35s
86:	learn: 0.5491562	total: 14.8s	remaining: 2m 35s
87:	learn: 0.5483042	total: 15s	remaining: 2m 35s
88:	learn: 0.5470834	total: 15.2s	remaining: 2m 35s
89:	learn: 0.5462725	total: 15.3s	remaining: 2m 34s
90:	learn: 0.5449933	total: 15.5s	remaining: 2m 34s
91:	learn: 0.5438163	total: 15.6s	remaining: 2m 34s
92:	learn: 0.5428196	total: 15.8s	remaining: 2m 33s
93:	learn: 0.5416969	total: 16s	remaining: 2m 33s
94:	learn: 0.5406829	total: 16.1s	remaining: 2m 33s
95:	learn: 0.5395101	total: 16.3s	remaining: 2m 33s
96:	learn: 0.5376999	total: 16.5s	remaining: 2m 33s
97:	learn: 0.5368509	total: 16.7s	remaining: 2m 33s
98:	learn: 0.5356296	total: 16.9s	remaining: 2m 33s
99:	learn: 0.5349742	total: 17s	remaining: 2m 33s
100:	learn: 0.5339947	total: 17.2s	remaining: 2m 32s
101:	learn: 0.5328416	total: 17.4s	remaining: 2m 32s
102:	learn: 0.5318973	total: 17.5s	remaining: 2m 32s
103:	learn: 0.5302500	total: 17.7s	remaining: 2m 32s
104:	learn: 0.5296633	total: 17.9s	remaining: 2m 32s
105:	learn: 0.5285259	total: 18s	remaining: 2m 32s
106:	learn: 0.5280117	total: 18.2s	remaining: 2m 31s
107:	learn: 0.5266825	total: 18.4s	remaining: 2m 31s
108:	learn: 0.5256324	total: 18.5s	remaining: 2m 31s
109:	learn: 0.5249724	total: 18.7s	remaining: 2m 31s
110:	learn: 0.5242379	total: 18.9s	remaining: 2m 31s
111:	learn: 0.5227402	total: 19.1s	remaining: 2m 31s
112:	learn: 0.5220735	total: 19.2s	remaining: 2m 30s
113:	learn: 0.5210994	total: 19.4s	remaining: 2m 30s
114:	learn: 0.5202465	total: 19.5s	remaining: 2m 30s
115:	learn: 0.5195023	total: 19.7s	remaining: 2m 30s
116:	learn: 0.5183200	total: 19.9s	remaining: 2m 30s
117:	learn: 0.5170314	total: 20s	remaining: 2m 29s
118:	learn: 0.5163531	total: 20.2s	remaining: 2m 29s
119:	learn: 0.5156379	total: 20.4s	remaining: 2m 29s
120:	learn: 0.5142868	total: 20.6s	remaining: 2m 29s
121:	learn: 0.5136898	total: 20.8s	remaining: 2m 29s
122:	learn: 0.5128035	total: 20.9s	remaining: 2m 29s
123:	learn: 0.5121580	total: 21.1s	remaining: 2m 29s
124:	learn: 0.5115125	total: 21.3s	remaining: 2m 28s
125:	learn: 0.5108430	total: 21.4s	remaining: 2m 28s
126:	learn: 0.5102419	total: 21.6s	remaining: 2m 28s
127:	learn: 0.5094630	total: 21.7s	remaining: 2m 27s
128:	learn: 0.5088270	total: 21.9s	remaining: 2m 27s
129:	learn: 0.5076892	total: 22s	remaining: 2m 27s
130:	learn: 0.5068285	total: 22.2s	remaining: 2m 27s
131:	learn: 0.5059025	total: 22.4s	remaining: 2m 27s
132:	learn: 0.5054593	total: 22.6s	remaining: 2m 27s
133:	learn: 0.5046525	total: 22.7s	remaining: 2m 26s
134:	learn: 0.5041223	total: 22.9s	remaining: 2m 26s
135:	learn: 0.5035603	total: 23s	remaining: 2m 26s
136:	learn: 0.5030968	total: 23.2s	remaining: 2m 26s
137:	learn: 0.5021539	total: 23.4s	remaining: 2m 25s
138:	learn: 0.5016888	total: 23.5s	remaining: 2m 25s
139:	learn: 0.5009898	total: 23.7s	remaining: 2m 25s
140:	learn: 0.5006000	total: 23.9s	remaining: 2m 25s
141:	learn: 0.4995549	total: 24s	remaining: 2m 25s
142:	learn: 0.4987092	total: 24.2s	remaining: 2m 24s
143:	learn: 0.4977870	total: 24.3s	remaining: 2m 24s
144:	learn: 0.4970762	total: 24.5s	remaining: 2m 24s
145:	learn: 0.4962540	total: 24.7s	remaining: 2m 24s
146:	learn: 0.4957694	total: 24.8s	remaining: 2m 24s
147:	learn: 0.4953558	total: 25s	remaining: 2m 23s
148:	learn: 0.4946095	total: 25.2s	remaining: 2m 23s
149:	learn: 0.4939625	total: 25.3s	remaining: 2m 23s
150:	learn: 0.4932092	total: 25.5s	remaining: 2m 23s
151:	learn: 0.4925712	total: 25.7s	remaining: 2m 23s
152:	learn: 0.4915678	total: 25.8s	remaining: 2m 23s
153:	learn: 0.4911123	total: 26s	remaining: 2m 22s
154:	learn: 0.4906864	total: 26.1s	remaining: 2m 22s
155:	learn: 0.4900861	total: 26.3s	remaining: 2m 22s
156:	learn: 0.4896671	total: 26.5s	remaining: 2m 22s
157:	learn: 0.4891709	total: 26.6s	remaining: 2m 21s
158:	learn: 0.4886198	total: 26.8s	remaining: 2m 21s
159:	learn: 0.4878284	total: 27s	remaining: 2m 21s
160:	learn: 0.4870076	total: 27.2s	remaining: 2m 21s
161:	learn: 0.4865573	total: 27.3s	remaining: 2m 21s
162:	learn: 0.4855635	total: 27.5s	remaining: 2m 21s
163:	learn: 0.4851161	total: 27.7s	remaining: 2m 21s
164:	learn: 0.4844134	total: 27.8s	remaining: 2m 20s
165:	learn: 0.4835693	total: 28s	remaining: 2m 20s
166:	learn: 0.4832094	total: 28.2s	remaining: 2m 20s
167:	learn: 0.4823528	total: 28.3s	remaining: 2m 20s
168:	learn: 0.4815574	total: 28.5s	remaining: 2m 20s
169:	learn: 0.4809463	total: 28.7s	remaining: 2m 20s
170:	learn: 0.4801709	total: 28.9s	remaining: 2m 19s
171:	learn: 0.4797010	total: 29s	remaining: 2m 19s
172:	learn: 0.4790652	total: 29.2s	remaining: 2m 19s
173:	learn: 0.4785290	total: 29.3s	remaining: 2m 19s
174:	learn: 0.4779456	total: 29.5s	remaining: 2m 19s
175:	learn: 0.4768878	total: 29.7s	remaining: 2m 19s
176:	learn: 0.4761950	total: 29.9s	remaining: 2m 18s
177:	learn: 0.4757411	total: 30s	remaining: 2m 18s
178:	learn: 0.4750281	total: 30.2s	remaining: 2m 18s
179:	learn: 0.4745719	total: 30.4s	remaining: 2m 18s
180:	learn: 0.4742411	total: 30.6s	remaining: 2m 18s
181:	learn: 0.4738676	total: 30.8s	remaining: 2m 18s
182:	learn: 0.4731809	total: 30.9s	remaining: 2m 18s
183:	learn: 0.4728918	total: 31.1s	remaining: 2m 17s
184:	learn: 0.4723810	total: 31.3s	remaining: 2m 17s
185:	learn: 0.4719858	total: 31.4s	remaining: 2m 17s
186:	learn: 0.4713033	total: 31.6s	remaining: 2m 17s
187:	learn: 0.4709483	total: 31.7s	remaining: 2m 17s
188:	learn: 0.4704764	total: 31.9s	remaining: 2m 16s
189:	learn: 0.4697508	total: 32.1s	remaining: 2m 16s
190:	learn: 0.4692034	total: 32.2s	remaining: 2m 16s
191:	learn: 0.4687883	total: 32.4s	remaining: 2m 16s
192:	learn: 0.4681053	total: 32.6s	remaining: 2m 16s
193:	learn: 0.4676772	total: 32.7s	remaining: 2m 15s
194:	learn: 0.4669692	total: 32.9s	remaining: 2m 15s
195:	learn: 0.4662590	total: 33.1s	remaining: 2m 15s
196:	learn: 0.4656865	total: 33.2s	remaining: 2m 15s
197:	learn: 0.4652096	total: 33.4s	remaining: 2m 15s
198:	learn: 0.4647527	total: 33.6s	remaining: 2m 15s
199:	learn: 0.4641243	total: 33.7s	remaining: 2m 14s
200:	learn: 0.4636863	total: 33.9s	remaining: 2m 14s
201:	learn: 0.4632808	total: 34.1s	remaining: 2m 14s
202:	learn: 0.4625828	total: 34.3s	remaining: 2m 14s
203:	learn: 0.4621613	total: 34.4s	remaining: 2m 14s
204:	learn: 0.4618263	total: 34.6s	remaining: 2m 14s
205:	learn: 0.4614761	total: 34.7s	remaining: 2m 13s
206:	learn: 0.4610094	total: 34.9s	remaining: 2m 13s
207:	learn: 0.4604316	total: 35.1s	remaining: 2m 13s
208:	learn: 0.4597213	total: 35.3s	remaining: 2m 13s
209:	learn: 0.4595706	total: 35.4s	remaining: 2m 13s
210:	learn: 0.4592093	total: 35.6s	remaining: 2m 12s
211:	learn: 0.4588430	total: 35.7s	remaining: 2m 12s
212:	learn: 0.4584184	total: 35.9s	remaining: 2m 12s
213:	learn: 0.4580001	total: 36.1s	remaining: 2m 12s
214:	learn: 0.4572892	total: 36.2s	remaining: 2m 12s
215:	learn: 0.4570085	total: 36.4s	remaining: 2m 12s
216:	learn: 0.4565801	total: 36.5s	remaining: 2m 11s
217:	learn: 0.4559435	total: 36.7s	remaining: 2m 11s
218:	learn: 0.4554978	total: 36.9s	remaining: 2m 11s
219:	learn: 0.4546292	total: 37.1s	remaining: 2m 11s
220:	learn: 0.4540094	total: 37.2s	remaining: 2m 11s
221:	learn: 0.4536120	total: 37.4s	remaining: 2m 11s
222:	learn: 0.4530158	total: 37.6s	remaining: 2m 10s
223:	learn: 0.4525250	total: 37.7s	remaining: 2m 10s
224:	learn: 0.4521131	total: 37.9s	remaining: 2m 10s
225:	learn: 0.4515880	total: 38.1s	remaining: 2m 10s
226:	learn: 0.4512449	total: 38.2s	remaining: 2m 10s
227:	learn: 0.4505930	total: 38.4s	remaining: 2m 10s
228:	learn: 0.4501994	total: 38.6s	remaining: 2m 9s
229:	learn: 0.4497730	total: 38.7s	remaining: 2m 9s
230:	learn: 0.4494892	total: 38.9s	remaining: 2m 9s
231:	learn: 0.4490571	total: 39.1s	remaining: 2m 9s
232:	learn: 0.4486995	total: 39.2s	remaining: 2m 9s
233:	learn: 0.4479736	total: 39.4s	remaining: 2m 8s
234:	learn: 0.4472356	total: 39.6s	remaining: 2m 8s
235:	learn: 0.4466342	total: 39.8s	remaining: 2m 8s
236:	learn: 0.4462965	total: 39.9s	remaining: 2m 8s
237:	learn: 0.4458865	total: 40.1s	remaining: 2m 8s
238:	learn: 0.4452053	total: 40.3s	remaining: 2m 8s
239:	learn: 0.4448368	total: 40.5s	remaining: 2m 8s
240:	learn: 0.4444913	total: 40.6s	remaining: 2m 7s
241:	learn: 0.4442380	total: 40.8s	remaining: 2m 7s
242:	learn: 0.4438473	total: 41s	remaining: 2m 7s
243:	learn: 0.4434528	total: 41.1s	remaining: 2m 7s
244:	learn: 0.4429539	total: 41.3s	remaining: 2m 7s
245:	learn: 0.4424536	total: 41.5s	remaining: 2m 7s
246:	learn: 0.4421829	total: 41.6s	remaining: 2m 6s
247:	learn: 0.4415487	total: 41.8s	remaining: 2m 6s
248:	learn: 0.4412038	total: 42s	remaining: 2m 6s
249:	learn: 0.4409440	total: 42.1s	remaining: 2m 6s
250:	learn: 0.4403194	total: 42.3s	remaining: 2m 6s
251:	learn: 0.4400200	total: 42.5s	remaining: 2m 6s
252:	learn: 0.4397273	total: 42.6s	remaining: 2m 5s
253:	learn: 0.4393052	total: 42.8s	remaining: 2m 5s
254:	learn: 0.4389360	total: 43s	remaining: 2m 5s
255:	learn: 0.4384291	total: 43.2s	remaining: 2m 5s
256:	learn: 0.4382433	total: 43.3s	remaining: 2m 5s
257:	learn: 0.4374533	total: 43.5s	remaining: 2m 5s
258:	learn: 0.4371482	total: 43.7s	remaining: 2m 4s
259:	learn: 0.4365690	total: 43.8s	remaining: 2m 4s
260:	learn: 0.4364880	total: 44s	remaining: 2m 4s
261:	learn: 0.4361493	total: 44.1s	remaining: 2m 4s
262:	learn: 0.4358125	total: 44.3s	remaining: 2m 4s
263:	learn: 0.4354786	total: 44.5s	remaining: 2m 3s
264:	learn: 0.4350344	total: 44.7s	remaining: 2m 3s
265:	learn: 0.4347078	total: 44.8s	remaining: 2m 3s
266:	learn: 0.4343532	total: 45s	remaining: 2m 3s
267:	learn: 0.4340453	total: 45.2s	remaining: 2m 3s
268:	learn: 0.4337791	total: 45.3s	remaining: 2m 3s
269:	learn: 0.4333495	total: 45.5s	remaining: 2m 3s
270:	learn: 0.4330292	total: 45.7s	remaining: 2m 2s
271:	learn: 0.4325862	total: 45.8s	remaining: 2m 2s
272:	learn: 0.4323350	total: 46s	remaining: 2m 2s
273:	learn: 0.4317896	total: 46.2s	remaining: 2m 2s
274:	learn: 0.4314756	total: 46.3s	remaining: 2m 2s
275:	learn: 0.4310792	total: 46.5s	remaining: 2m 1s
276:	learn: 0.4309180	total: 46.7s	remaining: 2m 1s
277:	learn: 0.4305155	total: 46.8s	remaining: 2m 1s
278:	learn: 0.4301216	total: 47s	remaining: 2m 1s
279:	learn: 0.4298545	total: 47.2s	remaining: 2m 1s
280:	learn: 0.4294736	total: 47.4s	remaining: 2m 1s
281:	learn: 0.4290476	total: 47.6s	remaining: 2m 1s
282:	learn: 0.4286301	total: 47.7s	remaining: 2m
283:	learn: 0.4281722	total: 47.9s	remaining: 2m
284:	learn: 0.4277132	total: 48.1s	remaining: 2m
285:	learn: 0.4273015	total: 48.2s	remaining: 2m
286:	learn: 0.4267658	total: 48.4s	remaining: 2m
287:	learn: 0.4265451	total: 48.6s	remaining: 2m
288:	learn: 0.4260363	total: 48.7s	remaining: 1m 59s
289:	learn: 0.4256281	total: 48.9s	remaining: 1m 59s
290:	learn: 0.4252214	total: 49.1s	remaining: 1m 59s
291:	learn: 0.4245764	total: 49.3s	remaining: 1m 59s
292:	learn: 0.4242984	total: 49.4s	remaining: 1m 59s
293:	learn: 0.4240074	total: 49.6s	remaining: 1m 59s
294:	learn: 0.4235067	total: 49.8s	remaining: 1m 58s
295:	learn: 0.4232251	total: 49.9s	remaining: 1m 58s
296:	learn: 0.4229744	total: 50.1s	remaining: 1m 58s
297:	learn: 0.4226765	total: 50.3s	remaining: 1m 58s
298:	learn: 0.4220595	total: 50.5s	remaining: 1m 58s
299:	learn: 0.4215476	total: 50.7s	remaining: 1m 58s
300:	learn: 0.4212058	total: 50.8s	remaining: 1m 58s
301:	learn: 0.4208539	total: 51s	remaining: 1m 57s
302:	learn: 0.4204763	total: 51.2s	remaining: 1m 57s
303:	learn: 0.4201293	total: 51.4s	remaining: 1m 57s
304:	learn: 0.4196835	total: 51.5s	remaining: 1m 57s
305:	learn: 0.4194990	total: 51.7s	remaining: 1m 57s
306:	learn: 0.4188357	total: 51.9s	remaining: 1m 57s
307:	learn: 0.4185872	total: 52s	remaining: 1m 56s
308:	learn: 0.4182285	total: 52.2s	remaining: 1m 56s
309:	learn: 0.4179080	total: 52.4s	remaining: 1m 56s
310:	learn: 0.4176194	total: 52.5s	remaining: 1m 56s
311:	learn: 0.4171575	total: 52.7s	remaining: 1m 56s
312:	learn: 0.4168828	total: 52.9s	remaining: 1m 56s
313:	learn: 0.4165381	total: 53.1s	remaining: 1m 55s
314:	learn: 0.4162699	total: 53.2s	remaining: 1m 55s
315:	learn: 0.4158060	total: 53.4s	remaining: 1m 55s
316:	learn: 0.4156051	total: 53.6s	remaining: 1m 55s
317:	learn: 0.4152332	total: 53.8s	remaining: 1m 55s
318:	learn: 0.4150185	total: 53.9s	remaining: 1m 55s
319:	learn: 0.4146132	total: 54.1s	remaining: 1m 54s
320:	learn: 0.4142080	total: 54.3s	remaining: 1m 54s
321:	learn: 0.4138663	total: 54.5s	remaining: 1m 54s
322:	learn: 0.4135701	total: 54.6s	remaining: 1m 54s
323:	learn: 0.4133928	total: 54.8s	remaining: 1m 54s
324:	learn: 0.4129999	total: 54.9s	remaining: 1m 54s
325:	learn: 0.4127875	total: 55.1s	remaining: 1m 53s
326:	learn: 0.4125277	total: 55.3s	remaining: 1m 53s
327:	learn: 0.4122321	total: 55.4s	remaining: 1m 53s
328:	learn: 0.4120476	total: 55.6s	remaining: 1m 53s
329:	learn: 0.4117952	total: 55.8s	remaining: 1m 53s
330:	learn: 0.4115805	total: 55.9s	remaining: 1m 53s
331:	learn: 0.4112412	total: 56.1s	remaining: 1m 52s
332:	learn: 0.4107421	total: 56.3s	remaining: 1m 52s
333:	learn: 0.4104468	total: 56.5s	remaining: 1m 52s
334:	learn: 0.4101101	total: 56.6s	remaining: 1m 52s
335:	learn: 0.4098764	total: 56.8s	remaining: 1m 52s
336:	learn: 0.4096124	total: 57s	remaining: 1m 52s
337:	learn: 0.4091699	total: 57.1s	remaining: 1m 51s
338:	learn: 0.4089215	total: 57.3s	remaining: 1m 51s
339:	learn: 0.4086766	total: 57.5s	remaining: 1m 51s
340:	learn: 0.4084865	total: 57.6s	remaining: 1m 51s
341:	learn: 0.4081268	total: 57.8s	remaining: 1m 51s
342:	learn: 0.4079441	total: 58s	remaining: 1m 51s
343:	learn: 0.4076781	total: 58.1s	remaining: 1m 50s
344:	learn: 0.4071663	total: 58.3s	remaining: 1m 50s
345:	learn: 0.4069791	total: 58.5s	remaining: 1m 50s
346:	learn: 0.4067798	total: 58.6s	remaining: 1m 50s
347:	learn: 0.4063175	total: 58.8s	remaining: 1m 50s
348:	learn: 0.4059941	total: 59s	remaining: 1m 49s
349:	learn: 0.4053593	total: 59.1s	remaining: 1m 49s
350:	learn: 0.4048087	total: 59.3s	remaining: 1m 49s
351:	learn: 0.4045107	total: 59.5s	remaining: 1m 49s
352:	learn: 0.4042328	total: 59.7s	remaining: 1m 49s
353:	learn: 0.4038685	total: 59.9s	remaining: 1m 49s
354:	learn: 0.4035814	total: 1m	remaining: 1m 49s
355:	learn: 0.4034297	total: 1m	remaining: 1m 48s
356:	learn: 0.4031756	total: 1m	remaining: 1m 48s
357:	learn: 0.4029092	total: 1m	remaining: 1m 48s
358:	learn: 0.4024291	total: 1m	remaining: 1m 48s
359:	learn: 0.4021976	total: 1m	remaining: 1m 48s
360:	learn: 0.4018878	total: 1m 1s	remaining: 1m 48s
361:	learn: 0.4016997	total: 1m 1s	remaining: 1m 47s
362:	learn: 0.4014944	total: 1m 1s	remaining: 1m 47s
363:	learn: 0.4010846	total: 1m 1s	remaining: 1m 47s
364:	learn: 0.4007365	total: 1m 1s	remaining: 1m 47s
365:	learn: 0.4003922	total: 1m 1s	remaining: 1m 47s
366:	learn: 0.3999739	total: 1m 2s	remaining: 1m 47s
367:	learn: 0.3996172	total: 1m 2s	remaining: 1m 46s
368:	learn: 0.3993321	total: 1m 2s	remaining: 1m 46s
369:	learn: 0.3992026	total: 1m 2s	remaining: 1m 46s
370:	learn: 0.3988607	total: 1m 2s	remaining: 1m 46s
371:	learn: 0.3985317	total: 1m 2s	remaining: 1m 46s
372:	learn: 0.3982748	total: 1m 3s	remaining: 1m 46s
373:	learn: 0.3981088	total: 1m 3s	remaining: 1m 45s
374:	learn: 0.3979301	total: 1m 3s	remaining: 1m 45s
375:	learn: 0.3977948	total: 1m 3s	remaining: 1m 45s
376:	learn: 0.3974116	total: 1m 3s	remaining: 1m 45s
377:	learn: 0.3972534	total: 1m 3s	remaining: 1m 45s
378:	learn: 0.3969487	total: 1m 4s	remaining: 1m 45s
379:	learn: 0.3967791	total: 1m 4s	remaining: 1m 44s
380:	learn: 0.3964665	total: 1m 4s	remaining: 1m 44s
381:	learn: 0.3961564	total: 1m 4s	remaining: 1m 44s

In [30]:
catModel_y_pre = cat_model.predict(x_test1)

In [31]:
accuracy_score(y_test1,catModel_y_pre)

0.8817468331191481

In [32]:
cat_model.score(xtrain1,ytrain1)

0.8902382052971665

# LightGBM

In [33]:
lgbm = LGBMClassifier(random_state=42)
lgbm.fit(xtrain1,ytrain1)

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2266
[LightGBM] [Info] Number of data points in the train set: 406708, number of used features: 53
[LightGBM] [Info] Start training from score -1.008966
[LightGBM] [Info] Start training from score -0.718703
[LightGBM] [Info] Start training from score -2.784590
[LightGBM] [Info] Start training from score -5.339241
[LightGBM] [Info] Start training from score -4.128325
[LightGBM] [Info] Start training from score -3.511590
[LightGBM] [Info] Start training from score -3.338024

LGBMClassifier(random_state=42)

In [34]:
lgbm_y_pre = lgbm.predict(x_test1)

In [35]:
accuracy_score(y_test1,lgbm_y_pre)

0.8555741692674866

In [36]:
lgbm.score(xtrain1,ytrain1)

0.8671897282571279